// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALp6qFViE7zsJuCBToH9N5FzNx7fxyJjU',
    appId: '1:931284334624:web:5a81bed644accf78cb2445',
    messagingSenderId: '931284334624',
    projectId: 'chatter-e0ce9',
    authDomain: 'chatter-e0ce9.firebaseapp.com',
    storageBucket: 'chatter-e0ce9.appspot.com',
    measurementId: 'G-VXYV89XF2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGS3boP93ILw_3gQI34PaYUTIwF2wbDnI',
    appId: '1:931284334624:android:a55907e3d05aab26cb2445',
    messagingSenderId: '931284334624',
    projectId: 'chatter-e0ce9',
    storageBucket: 'chatter-e0ce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAranaPXgozEyUQKZ2GMxnyA9-IofPlaoQ',
    appId: '1:931284334624:ios:dffd16ea8e8461eecb2445',
    messagingSenderId: '931284334624',
    projectId: 'chatter-e0ce9',
    storageBucket: 'chatter-e0ce9.appspot.com',
    iosBundleId: 'com.example.chatter',
  );
}
